### ISSUE TITLE
Port to python-mpd2 / fork?

### ISSUE THREAD

**Issue by alphapapa** [nickpegg/mpdsync#4]
Hey, I have updated the script to work with python-mpd2 (which supports some newer commands and ranges).  The branch is at https://github.com/alphapapa/mpdsync/tree/python-mpd2.  I also rewrote a lot of it, subclassing `MPDClient`, using `argparse` instead of a config file, using CamelCase for names (just my preference), and org-mode for the readme (also just my preference).  I did also fix one bug I discovered while working on it, which is that if a track were deleted from the playlist that's before the currently playing track, slaves would stop playing.

Oh, and I used `logging`, which picks up debug messages from `python-mpd` too.

This is a drastic change, so I understand if you don't want to pull the branch.  If that's the case, would you want me to rename it to something other than `mpdsync`?  I could do something like `ampdsync` or `mpdsync2`.  Let me know what you think.

**Comment by alphapapa** [comment]
FYI, I've been continuing to work on it.  I've added a lot of code to optionally try to keep the track position in sync on the master and the slaves.  It's far from perfect, but I hope it will become more useful as I continue to refine it.  I'd welcome your help on it if you're interested.  If not, I should probably officially fork it and rename it.  Just let me know.

P.S.  I know you probably have more important things to do, so if I don't hear from you in a week or so, I'll go ahead and fork it.  :)

**Comment by alphapapa** [comment]
Well, it's been a bit more than a week... ;)  But anyway, I see you're still active on GitHub, so...ping?

**Comment by nickpegg** [comment]
Hey! Sorry about forgetting about this. I don't really use this script anymore and it looks like you're pretty active on it (at least on the `python-mpd2` branch), so I'm willing to call your fork the authoritative one. I believe the customary thing is for me to update the README on repo to point users toward your repo. You already have a nod towards me in your README, which is all I ask that you have. :)

If that sounds good to you, I'll update my README to point people at https://github.com/alphapapa/mpdsync and you can merge your `python-mpd2` branch into your master.

**Comment by alphapapa** [comment]
No problem!  I'm using it pretty regularly, so I'd be happy to assume stewardship of the project.  Thanks for making it in the first place, it was a great foundation for me to build on!  Please feel free to contribute in the future if you find yourself using it again.  :)
